language: python

dist: trusty

sudo: required

services:
  - docker

matrix:
  include:
  - python: "2.7"
    env: NUMPY_VERSION=1.7.1
  - python: "3.6"
    env: NUMPY_VERSION=1.7.1
  - python: "3.6"
    env: NUMPY_VERSION=1.12.1

install:
  - docker build -t test-container --build-arg numpy_version=$NUMPY_VERSION .

script:
  - docker run -v $PWD:$PWD test-container /bin/bash -c "cd $PWD && pytest"
